name: laravel-mysql

services:
  # User is root by default
  db:
    image: dhi.io/mysql:${MYSQL_VERSION:-9}
    restart: always
    ports:
      - "${MYSQL_PORT:-8001}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command: mysqld
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - backend

  cache:
    image: dhi.io/valkey:9
    restart: always
    environment:
      VALKEY_PASSWORD: "${VALKEY_PASSWORD}"
      VALKEY_USER: "${VALKEY_USER:-root}"
    ports:
      - "${VALKEY_PORT:-8002:6380}"
    volumes:
      - "./config/valkey/valkey.conf:/tmp/valkey.conf:ro"
      - "./entrypoints/init-valkey.sh:/usr/local/bin/entrypoint.sh"
      - "valkey-data:/data"
    command: valkey-server /tmp/valkey.conf
    networks:
      - backend

volumes:
  mysql-data:
  valkey-data:

networks:
  backend:

