name: laravel-mysql

services:
  # User is root by default
  db:
    build:
      context: .
      dockerfile: docker/mysql.dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    restart: always
    ports:
      - "${MYSQL_PORT:-8001}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  cache:
    build:
      context: .
      dockerfile: docker/valkey.dockerfile
      args:
        - VALKEY_VERSION=${VALKEY_VERSION}
    restart: always
    ports:
      - "${VALKEY_PORT:-8003}:6380"
    secrets:
      - valkey_password
    volumes:
      - "valkey-data:/data"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "valkey-cli", "-p", "6380", "ping"]
      interval: 5s
      timeout: 3s
      retries: 4

volumes:
  mysql-data:
  valkey-data:

networks:
  backend:
    driver: bridge

secrets:
  mysql_root_password:
    environment: MYSQL_ROOT_PASSWORD
  valkey_password:
    environment: VALKEY_PASSWORD
